baseURL = 'https://ahbab-travel-and-tours.github.io/'
languageCode = 'en-us'
title = 'AHBAB TRAVEL & TOURS'
#theme = 'devfest-theme-hugo'
theme = 'ahbab-travels-tours-theme'


enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

relativeURLs = true
canonifyURLs = true

[params]
    title = "AHBAB TRAVEL & TOURS"
    date = "2024-12-10"
    description = "A Hajj Umrah Travel Agency."
    email = "ahbabtravels@yahoo.com"
    keywords = "travel, hajj, umrah, islam, pilgrimage"
    copyright = "All Rights Reserved © 2024 AHBAB Travel & TOURS"
    cfpUrl = "https://callforpapers.com/submit"
    subscriptionUrl = "https://wa.me/923645110066"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    #manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"
    customCSS = ["custom.css", "carousel.css"]
    

[params.logos]
    jumbo  = "/images/logos/devfest_color_text.svg"
    header = "/images/logos/devfest_color_text.svg"
    footer = "/images/logos/devfest_color_text.svg"

[menu]
[[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 100
    external = false
[[menu.main]]
    identifier = "get-started"
    name = "Getting Started"
    url = "/get-started/"
    weight = 60
    external = false
[[menu.main]]
    identifier = "hajj-umrah"
    name = "Hajj & Umrah Packages"
    url = "/hajj-umrah/"
    weight = 50
    external = false
[[menu.main]]
    identifier = "hotels"
    name = "Hotels"
    url = "/hotels/"
    weight = 70
    external = false
[[menu.main]]
    identifier = "news"
    name = "News & Updates"
    url = "/news/"
    weight = 90
    external = false

[[menu.main]]
    identifier = "faq"
    name = "FAQs"
    url = "/faq/"
    weight = 90
    external = false
[[menu.main]]
    identifier = "contact"
    name = "Contact "
    url = "/contact/"
    weight = 100
    external = false

[languages]
[languages.en]
    weight = 1
    languageName = "English"


#[languages.fr]
#    weight = 2
#    languageName = "fr"

#[languages.fr.params]
#    description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs. Elle s'adresse aussi bien aux étudiants, aux professionnels ou tout simplement aux curieux technophiles."

[taxonomies]
  tag = "tags"
